### PR TITLE
Todo testing

### PR DESCRIPTION
**Pull request by najibullahjafari**
Here:

- We used  jest framework for testing.
- We create a file by the name of functions.test.js
- We used the mock storage.
PcBangingGIF(2)

**Happy coding 🎈🎉😊**

### CODE REVIEW

**Review by julie-ify — COMMENTED** [review]
Hi @najibullahjafari and @MasumaJaffery, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly pay attention to the form/project you are submitting. This project only contains tests for edit, update and clear completed but you submitted the Part 1 project which is meant for add and remove functions. Kindly verify your submission.

* Your link in the live demo section is not the deployed link. Kindly deploy the app or remove that section.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by najibullahjafari** [comment]
@julie-ify 
Hello,
Thank you for reviewing my project!
According to requirement I have made functions.test.js to test edit, update and clear completed functions that they really work.
Can you tell the exact mistake I have did?

**Comment by MasumaJaffery** [comment]
You only need to add tests for Add and Remove for Part 1 Testing,
Actually you add edit and clear all functionality too!
Remove for part 1!

**Review by V-Blaze — APPROVED** [review]
Hi @najibullahjafari , @MasumaJaffery 

# Approved 🍏 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
green-lantern-ok

## Highlights
- Tests are passing✔✔
- Wrote test for `add and remove` functions :heavy_check_mark: 
- Clean and well organized code :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
